// <auto-generated />
using System;
using LMS.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LMS.Infrastructure.Migrations;

[DbContext(typeof(LmsDbContext))]
[Migration("20260825120000_CreateAuthTables")]
partial class CreateAuthTables
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "8.0.8")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity(
            "LMS.Infrastructure.Data.Entities.User",
            b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid")
                    .HasColumnName("id")
                    .HasDefaultValueSql("gen_random_uuid()");

                b.Property<DateTime>("CreatedAt")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("timestamptz")
                    .HasColumnName("created_at")
                    .HasDefaultValueSql("NOW()");

                b.Property<DateTime?>("DeletedAt")
                    .HasColumnType("timestamptz")
                    .HasColumnName("deleted_at");

                b.Property<Guid?>("DepartmentId")
                    .HasColumnType("uuid")
                    .HasColumnName("department_id");

                b.Property<string>("Email")
                    .IsRequired()
                    .HasColumnType("varchar")
                    .HasColumnName("email");

                b.Property<int>("FailedAttempts")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer")
                    .HasColumnName("failed_attempts")
                    .HasDefaultValue(0);

                b.Property<DateTime?>("LockedAt")
                    .HasColumnType("timestamptz")
                    .HasColumnName("locked_at");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("varchar")
                    .HasColumnName("name");

                b.Property<string>("PasswordHash")
                    .HasColumnType("varchar")
                    .HasColumnName("password_hash");

                b.Property<string>("Role")
                    .IsRequired()
                    .ValueGeneratedOnAdd()
                    .HasColumnType("varchar")
                    .HasColumnName("role")
                    .HasDefaultValue("EMPLOYEE");

                b.Property<string>("Status")
                    .IsRequired()
                    .ValueGeneratedOnAdd()
                    .HasColumnType("varchar")
                    .HasColumnName("status")
                    .HasDefaultValue("Active");

                b.Property<DateTime>("UpdatedAt")
                    .ValueGeneratedOnAddOrUpdate()
                    .HasColumnType("timestamptz")
                    .HasColumnName("updated_at")
                    .HasDefaultValueSql("NOW()");

                b.HasKey("Id").HasName("PK_users");

                b.HasIndex("Email").IsUnique().HasDatabaseName("idx_users_email");

                b.HasIndex("Status").HasDatabaseName("idx_users_status");

                b.ToTable("users", (string)null);

                b.HasCheckConstraint(
                    "ck_users_role",
                    "role IN ('EMPLOYEE', 'MANAGER', 'HR_ADMIN', 'SUPER_ADMIN')"
                );
                b.HasCheckConstraint("ck_users_status", "status IN ('Active', 'Inactive', 'Locked')");
            }
        );

        modelBuilder.Entity(
            "LMS.Infrastructure.Data.Entities.RefreshToken",
            b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid")
                    .HasColumnName("id")
                    .HasDefaultValueSql("gen_random_uuid()");

                b.Property<DateTime>("CreatedAt")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("timestamptz")
                    .HasColumnName("created_at")
                    .HasDefaultValueSql("NOW()");

                b.Property<DateTime>("ExpiresAt")
                    .HasColumnType("timestamptz")
                    .HasColumnName("expires_at");

                b.Property<string>("IpAddress")
                    .IsRequired()
                    .HasColumnType("varchar")
                    .HasColumnName("ip_address");

                b.Property<DateTime?>("RevokedAt")
                    .HasColumnType("timestamptz")
                    .HasColumnName("revoked_at");

                b.Property<string>("TokenHash")
                    .IsRequired()
                    .HasColumnType("varchar")
                    .HasColumnName("token_hash");

                b.Property<DateTime>("UpdatedAt")
                    .ValueGeneratedOnAddOrUpdate()
                    .HasColumnType("timestamptz")
                    .HasColumnName("updated_at")
                    .HasDefaultValueSql("NOW()");

                b.Property<Guid>("UserId")
                    .HasColumnType("uuid")
                    .HasColumnName("user_id");

                b.HasKey("Id").HasName("PK_refresh_tokens");

                b.HasIndex("UserId").HasDatabaseName("idx_refresh_tokens_user_id");

                b.ToTable("refresh_tokens", (string)null);
            }
        );

        modelBuilder.Entity(
            "LMS.Infrastructure.Data.Entities.Rs256Key",
            b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid")
                    .HasColumnName("id")
                    .HasDefaultValueSql("gen_random_uuid()");

                b.Property<DateTime>("CreatedAt")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("timestamptz")
                    .HasColumnName("created_at")
                    .HasDefaultValueSql("NOW()");

                b.Property<bool>("IsActive")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("boolean")
                    .HasColumnName("is_active")
                    .HasDefaultValue(true);

                b.Property<string>("PrivateKeyEncrypted")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("private_key_encrypted");

                b.Property<string>("PublicKey")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("public_key");

                b.Property<DateTime>("UpdatedAt")
                    .ValueGeneratedOnAddOrUpdate()
                    .HasColumnType("timestamptz")
                    .HasColumnName("updated_at")
                    .HasDefaultValueSql("NOW()");

                b.HasKey("Id").HasName("PK_rs256_keys");

                b.ToTable("rs256_keys", (string)null);
            }
        );

        modelBuilder.Entity(
            "LMS.Infrastructure.Data.Entities.RefreshToken",
            b =>
            {
                b.HasOne("LMS.Infrastructure.Data.Entities.User", "User")
                    .WithMany("RefreshTokens")
                    .HasForeignKey("UserId")
                    .HasConstraintName("fk_refresh_tokens_users")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("User");
            }
        );

        modelBuilder.Entity(
            "LMS.Infrastructure.Data.Entities.User",
            b =>
            {
                b.Navigation("RefreshTokens");
            }
        );
#pragma warning restore 612, 618
    }
}
