// <auto-generated />
using System;
using LMS.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LMS.Infrastructure.Migrations;

[DbContext(typeof(LmsDbContext))]
partial class LmsDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "8.0.8")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity(
            "LMS.Infrastructure.Data.Entities.AuditLog",
            b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid")
                    .HasColumnName("id")
                    .HasDefaultValueSql("gen_random_uuid()");

                b.Property<string>("Action")
                    .IsRequired()
                    .HasColumnType("varchar")
                    .HasColumnName("action");

                b.Property<Guid?>("ActorId")
                    .HasColumnType("uuid")
                    .HasColumnName("actor_id");

                b.Property<string>("ActorEmail")
                    .HasColumnType("varchar")
                    .HasColumnName("actor_email");

                b.Property<string>("Changes")
                    .HasColumnType("text")
                    .HasColumnName("changes");

                b.Property<DateTime>("CreatedAt")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("timestamptz")
                    .HasColumnName("created_at")
                    .HasDefaultValueSql("NOW()");

                b.Property<string>("EntityId")
                    .IsRequired()
                    .HasColumnType("varchar")
                    .HasColumnName("entity_id");

                b.Property<string>("EntityType")
                    .IsRequired()
                    .HasColumnType("varchar")
                    .HasColumnName("entity_type");

                b.HasKey("Id").HasName("pk_audit_logs");

                b.HasIndex("ActorId").HasDatabaseName("idx_audit_logs_actor_id");
                b.HasIndex("EntityId").HasDatabaseName("idx_audit_logs_entity_id");
                b.HasIndex("EntityType").HasDatabaseName("idx_audit_logs_entity_type");

                b.ToTable("audit_logs", (string)null);
            }
        );

        modelBuilder.Entity(
            "LMS.Infrastructure.Data.Entities.Department",
            b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid")
                    .HasColumnName("id")
                    .HasDefaultValueSql("gen_random_uuid()");

                b.Property<string>("Code")
                    .IsRequired()
                    .HasColumnType("varchar(10)")
                    .HasColumnName("code");

                b.Property<DateTime>("CreatedAt")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("timestamptz")
                    .HasColumnName("created_at")
                    .HasDefaultValueSql("NOW()");

                b.Property<DateTime?>("DeletedAt")
                    .HasColumnType("timestamptz")
                    .HasColumnName("deleted_at");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("varchar")
                    .HasColumnName("name");

                b.Property<int>("OverlapLimit")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer")
                    .HasColumnName("overlap_limit")
                    .HasDefaultValue(2);

                b.Property<string>("Status")
                    .IsRequired()
                    .ValueGeneratedOnAdd()
                    .HasColumnType("varchar")
                    .HasColumnName("status")
                    .HasDefaultValue("Active");

                b.Property<DateTime>("UpdatedAt")
                    .ValueGeneratedOnAddOrUpdate()
                    .HasColumnType("timestamptz")
                    .HasColumnName("updated_at")
                    .HasDefaultValueSql("NOW()");

                b.HasKey("Id").HasName("PK_departments");

                b.HasIndex("Code").IsUnique().HasDatabaseName("idx_departments_code");
                b.HasIndex("Name").IsUnique().HasDatabaseName("idx_departments_name");
                b.HasIndex("Status").HasDatabaseName("idx_departments_status");

                b.ToTable("departments", (string)null);

                b.HasCheckConstraint("ck_departments_status", "status IN ('Active', 'Inactive')");
            }
        );

        modelBuilder.Entity(
            "LMS.Infrastructure.Data.Entities.RefreshToken",
            b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid")
                    .HasColumnName("id")
                    .HasDefaultValueSql("gen_random_uuid()");

                b.Property<DateTime>("CreatedAt")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("timestamptz")
                    .HasColumnName("created_at")
                    .HasDefaultValueSql("NOW()");

                b.Property<DateTime>("ExpiresAt")
                    .HasColumnType("timestamptz")
                    .HasColumnName("expires_at");

                b.Property<string>("IpAddress")
                    .IsRequired()
                    .HasColumnType("varchar")
                    .HasColumnName("ip_address");

                b.Property<DateTime?>("RevokedAt")
                    .HasColumnType("timestamptz")
                    .HasColumnName("revoked_at");

                b.Property<string>("TokenHash")
                    .IsRequired()
                    .HasColumnType("varchar")
                    .HasColumnName("token_hash");

                b.Property<DateTime>("UpdatedAt")
                    .ValueGeneratedOnAddOrUpdate()
                    .HasColumnType("timestamptz")
                    .HasColumnName("updated_at")
                    .HasDefaultValueSql("NOW()");

                b.Property<Guid>("UserId")
                    .HasColumnType("uuid")
                    .HasColumnName("user_id");

                b.HasKey("Id").HasName("PK_refresh_tokens");

                b.HasIndex("UserId").HasDatabaseName("idx_refresh_tokens_user_id");

                b.ToTable("refresh_tokens", (string)null);
            }
        );

        modelBuilder.Entity(
            "LMS.Infrastructure.Data.Entities.Rs256Key",
            b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid")
                    .HasColumnName("id")
                    .HasDefaultValueSql("gen_random_uuid()");

                b.Property<DateTime>("CreatedAt")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("timestamptz")
                    .HasColumnName("created_at")
                    .HasDefaultValueSql("NOW()");

                b.Property<bool>("IsActive")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("boolean")
                    .HasColumnName("is_active")
                    .HasDefaultValue(true);

                b.Property<string>("PrivateKeyEncrypted")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("private_key_encrypted");

                b.Property<string>("PublicKey")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("public_key");

                b.Property<DateTime>("UpdatedAt")
                    .ValueGeneratedOnAddOrUpdate()
                    .HasColumnType("timestamptz")
                    .HasColumnName("updated_at")
                    .HasDefaultValueSql("NOW()");

                b.HasKey("Id").HasName("PK_rs256_keys");

                b.ToTable("rs256_keys", (string)null);
            }
        );

        modelBuilder.Entity(
            "LMS.Infrastructure.Data.Entities.User",
            b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid")
                    .HasColumnName("id")
                    .HasDefaultValueSql("gen_random_uuid()");

                b.Property<DateTime>("CreatedAt")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("timestamptz")
                    .HasColumnName("created_at")
                    .HasDefaultValueSql("NOW()");

                b.Property<DateOnly?>("DateOfJoining")
                    .HasColumnType("date")
                    .HasColumnName("date_of_joining");

                b.Property<DateTime?>("DeletedAt")
                    .HasColumnType("timestamptz")
                    .HasColumnName("deleted_at");

                b.Property<Guid?>("DepartmentId")
                    .HasColumnType("uuid")
                    .HasColumnName("department_id");

                b.Property<string>("Email")
                    .IsRequired()
                    .HasColumnType("varchar")
                    .HasColumnName("email");

                b.Property<int>("FailedAttempts")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer")
                    .HasColumnName("failed_attempts")
                    .HasDefaultValue(0);

                b.Property<string>("JobTitle")
                    .HasColumnType("varchar")
                    .HasColumnName("job_title");

                b.Property<DateTime?>("LockedAt")
                    .HasColumnType("timestamptz")
                    .HasColumnName("locked_at");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("varchar")
                    .HasColumnName("name");

                b.Property<string>("PasswordHash")
                    .HasColumnType("varchar")
                    .HasColumnName("password_hash");

                b.Property<string>("Phone")
                    .HasColumnType("varchar")
                    .HasColumnName("phone");

                b.Property<Guid?>("ReportingManagerId")
                    .HasColumnType("uuid")
                    .HasColumnName("reporting_manager_id");

                b.Property<string>("Role")
                    .IsRequired()
                    .ValueGeneratedOnAdd()
                    .HasColumnType("varchar")
                    .HasColumnName("role")
                    .HasDefaultValue("EMPLOYEE");

                b.Property<string>("Status")
                    .IsRequired()
                    .ValueGeneratedOnAdd()
                    .HasColumnType("varchar")
                    .HasColumnName("status")
                    .HasDefaultValue("Active");

                b.Property<DateTime>("UpdatedAt")
                    .ValueGeneratedOnAddOrUpdate()
                    .HasColumnType("timestamptz")
                    .HasColumnName("updated_at")
                    .HasDefaultValueSql("NOW()");

                b.HasKey("Id").HasName("PK_users");

                b.HasIndex("DepartmentId").HasDatabaseName("idx_users_department_id");
                b.HasIndex("Email").IsUnique().HasDatabaseName("idx_users_email");
                b.HasIndex("ReportingManagerId").HasDatabaseName("idx_users_reporting_manager_id");
                b.HasIndex("Status").HasDatabaseName("idx_users_status");

                b.ToTable("users", (string)null);

                b.HasCheckConstraint(
                    "ck_users_role",
                    "role IN ('EMPLOYEE', 'MANAGER', 'HR_ADMIN', 'SUPER_ADMIN')"
                );
                b.HasCheckConstraint("ck_users_status", "status IN ('Active', 'Inactive', 'Locked')");
            }
        );

        modelBuilder.Entity(
            "LMS.Infrastructure.Data.Entities.RefreshToken",
            b =>
            {
                b.HasOne("LMS.Infrastructure.Data.Entities.User", "User")
                    .WithMany("RefreshTokens")
                    .HasForeignKey("UserId")
                    .HasConstraintName("fk_refresh_tokens_users")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("User");
            }
        );

        modelBuilder.Entity(
            "LMS.Infrastructure.Data.Entities.User",
            b =>
            {
                b.HasOne("LMS.Infrastructure.Data.Entities.Department", "Department")
                    .WithMany("Users")
                    .HasForeignKey("DepartmentId")
                    .HasConstraintName("fk_users_departments")
                    .OnDelete(DeleteBehavior.SetNull);

                b.HasOne("LMS.Infrastructure.Data.Entities.User", "ReportingManager")
                    .WithMany("DirectReports")
                    .HasForeignKey("ReportingManagerId")
                    .HasConstraintName("fk_users_reporting_manager")
                    .OnDelete(DeleteBehavior.SetNull);

                b.Navigation("Department");
                b.Navigation("DirectReports");
                b.Navigation("RefreshTokens");
                b.Navigation("ReportingManager");
            }
        );

        modelBuilder.Entity(
            "LMS.Infrastructure.Data.Entities.Department",
            b =>
            {
                b.Navigation("Users");
            }
        );
#pragma warning restore 612, 618
    }
}
